var gameOfDay =
{
    "game": {
        "gameType": 0,
        "platformId": 2900490,
        "CEId": "bafc13bb-3ff4-44ec-b31d-fbb1bab2df25",
        "name": "Overflower",
        "header": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2900490/header.jpg?t=1725010668",
        "genre": [
            "Strategy"
        ],
        "tier": 1,
        "points": 15,
        "secondaryPoints": 0,
        "medianPlaytime": 402,
        "createdAt": "2024-10-05T02:00:34.000Z",
        "updatedAt": "2026-10-02T03:51:33.000Z",
        "playersOvercompleted": 0,
        "playersCompleted": 4,
        "playersStarted": 0,
        "playersTotal": 17,
        "priceData": {
            "USD": {
                "initial": 299,
                "final": 299,
                "discountPercent": 0
            },
            "EUR": {
                "initial": 299,
                "final": 299,
                "discountPercent": 0
            },
            "GBP": {
                "initial": 249,
                "final": 249,
                "discountPercent": 0
            },
            "JPY": {
                "initial": 35000,
                "final": 35000,
                "discountPercent": 0
            },
            "AUD": {
                "initial": 450,
                "final": 450,
                "discountPercent": 0
            },
            "CAD": {
                "initial": 389,
                "final": 389,
                "discountPercent": 0
            }
        },
        "milestones": {
            "primary": 1,
            "primaryText": "Tipping Point [15\u2605]\nCreate a 10 petal flower.",
            "secondary": 0,
            "secondaryText": "",
            "community": 0,
            "communityText": "",
            "achievements": 5
        },
        "CETags": {
            "genre": [
                "Puzzle"
            ],
            "info": []
        },
        "gameTags": [
            "Casual",
            "Simulation",
            "Cozy",
            "Logic",
            "Match 3",
            "Minimalist",
            "Physics",
            "Strategy",
            "Puzzle",
            "Relaxing",
            "Management",
            "Cute",
            "2D",
            "Indie",
            "Colorful",
            "Atmospheric",
            "Wholesome",
            "Singleplayer",
            "Perma Death",
            "Arcade"
        ],
        "languages": {
            "english": "IAS",
            "french": "IAS",
            "german": "IAS",
            "italian": "IAS",
            "japanese": "IAS",
            "spanish": "IAS",
            "afrikaans": "IAS",
            "albanian": "IAS",
            "amharic": "IAS",
            "arabic": "IAS",
            "armenian": "IAS",
            "assamese": "IAS",
            "azerbaijani": "IAS",
            "bangla": "IAS",
            "basque": "IAS",
            "belarusian": "IAS",
            "bosnian": "IAS",
            "brazilian": "IAS",
            "bulgarian": "IAS",
            "catalan": "IAS",
            "cherokee": "IAS",
            "croatian": "IAS",
            "czech": "IAS",
            "danish": "IAS",
            "dari": "IAS",
            "dutch": "IAS",
            "estonian": "IAS",
            "filipino": "IAS",
            "finnish": "IAS",
            "galician": "IAS",
            "georgian": "IAS",
            "greek": "IAS",
            "gujarati": "IAS",
            "gurmukhi": "IAS",
            "hausa": "IAS",
            "hebrew": "IAS",
            "hindi": "IAS",
            "hungarian": "IAS",
            "icelandic": "IAS",
            "igbo": "IAS",
            "indonesian": "IAS",
            "irish": "IAS",
            "kannada": "IAS",
            "kazakh": "IAS",
            "khmer": "IAS",
            "kiche": "IAS",
            "kinyarwanda": "IAS",
            "konkani": "IAS",
            "koreana": "IAS",
            "kyrgyz": "IAS",
            "latam": "IAS",
            "latvian": "IAS",
            "lithuanian": "IAS",
            "luxembourgish": "IAS",
            "macedonian": "IAS",
            "malay": "IAS",
            "malayalam": "IAS",
            "maltese": "IAS",
            "maori": "IAS",
            "marathi": "IAS",
            "mongolian": "IAS",
            "nepali": "IAS",
            "norwegian": "IAS",
            "odia": "IAS",
            "persian": "IAS",
            "polish": "IAS",
            "portuguese": "IAS",
            "quechua": "IAS",
            "romanian": "IAS",
            "russian": "IAS",
            "schinese": "IAS",
            "scots": "IAS",
            "serbian": "IAS",
            "shahmukhi": "IAS",
            "sindhi": "IAS",
            "sinhala": "IAS",
            "slovak": "IAS",
            "slovenian": "IAS",
            "sorani": "IAS",
            "sotho": "IAS",
            "swahili": "IAS",
            "swedish": "IAS",
            "tajik": "IAS",
            "tamil": "IAS",
            "tatar": "IAS",
            "tchinese": "IAS",
            "telugu": "IAS",
            "thai": "IAS",
            "tigrinya": "IAS",
            "tswana": "IAS",
            "turkish": "IAS",
            "turkmen": "IAS",
            "ukrainian": "IAS",
            "urdu": "IAS",
            "uyghur": "IAS",
            "uzbek": "IAS",
            "valencian": "IAS",
            "vietnamese": "IAS",
            "welsh": "IAS",
            "wolof": "IAS",
            "xhosa": "IAS",
            "yoruba": "IAS",
            "zulu": "IAS"
        }
    }
}
var gameOfDayDate = '2026-10-05'